player playMove "AidlPpneMstpSnonWnonDnon_SleepC_layDown"; 
titleText ['Getting up in 10 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 9 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 8 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 7 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 6 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 5 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 4 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 3 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 2 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
titleText ['Getting up in 1 Seconds', 'PLAIN DOWN']; titlefadeout 1;
sleep 1; 
player playMove "AidlPpneMstpSnonWnonDnon_SleepC_standUp";
