if ((getPlayerUID player) in ["12345678"]) then 
	{
		titleText ["Hello Admin.  Welcome back.", "PLAIN DOWN", 3];
	} else
		    {
				titleText ["You are entering the tournament area, you have 10 minutes to leave!!!", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 9 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 8 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 7 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 6 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 5 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
	playSound "bl_detect";
	sleep 0.2;
    playSound "bl_detect";
				titleText ["You have 4 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 3 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
	playSound "bl_detect";
	sleep 0.2;
    playSound "bl_detect";
				titleText ["You have 2 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 60;
				titleText ["You have 1 minutes to leave the area...", "PLAIN DOWN", 3];
			sleep 15;
				titleText ["You have 45 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 15;
	playSound "bl_detect";
	sleep 0.2;
    playSound "bl_detect";
				titleText ["You have 30 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 15;
	playSound "bl_detect";
	sleep 0.2;
    playSound "bl_detect";
				titleText ["You have 15 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 5;
	playSound "bl_wave1";
	sleep 0.2;
    playSound "bl_hit1";
	sleep 0.5;
	playSound "bl_hit2";
				titleText ["You have 10 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 4;
				titleText ["You need to leave now...", "PLAIN DOWN", 3];
	playSound "bl_detect";
	sleep 0.2;
    playSound "bl_detect";
	sleep 0.2;
	playSound "ns_fx_drone1";
			sleep 1;
				titleText ["You have 5 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 1;
		player setDamage 0.1;	
			titleText ["You have 4 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 1;
		player setDamage 0.3;
				titleText ["You have 3 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 1;
		player setDamage 0.4;
				titleText ["You have 2 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 1;
		player setDamage 0.7;
				titleText ["You have 1 seconds to leave the area...", "PLAIN DOWN", 3];
			sleep 1;
				titleText ["Bye Bye.........","PLAIN DOWN", 3]

			playSound "bl_full";
				titleText["","WHITE OUT",1];  
				titleText["","WHITE IN",1]; 
				sleep 0.25;
			"dynamicBlur" ppEffectAdjust [3];
			"dynamicBlur" ppEffectCommit 5;
				sleep 5;
		player setDamage 1;
			};

	waitUntil {! (vehicle player in list _Basis)};
titleText ["Was it worth it ?.", "PLAIN DOWN", 3];