/**
 * English and French comments
 * Commentaires anglais et français
 * 
 * This file adds the ArmA 2 and Arrowhead objetcs in the configuration variables of the logistics system.
 * Fichier ajoutant les objets d'ArmA 2 et Arrowhead dans la configuration du système de logistique.
 * 
 * Important note : All the classes names which inherits from the ones used in configuration variables will be also available.
 * Note importante : Tous les noms de classes dérivant de celles utilisées dans les variables de configuration seront aussi valables.
 */

/****** TOW WITH VEHICLE / REMORQUER AVEC VEHICULE ******/

/**
 * List of class names of vehicles which can tow towable objects.
 * Liste des noms de classes des véhicules terrestres pouvant remorquer des objets remorquables.
 */
R3F_LOG_CFG_remorqueurs = R3F_LOG_CFG_remorqueurs +
[
	"TowingTractor",
	"Tractor",
	"Kamaz_Base",
	"MTVR",
	"GRAD_Base",
	"Ural_Base",
	"V3S_Base",
	"BRDM2_Base",
	"BTR90_Base",
	"GAZ_Vodnik_HMG",
	"LAV25_Base",
	"StrykerBase_EP1",
	"M2A2_Base",
	"MLRS",
"ArmoredSUV_PMC_DZ",
"car_hatchback",
"car_sedan",
"datsun1_civil_1_open",
"datsun1_civil_2_covered",
"datsun1_civil_3_open",
"Fishing_Boat",
"GAZ_Vodnik_DZ",
"GAZ_Vodnik_MedEvac",
"GLT_M300_LT",
"GLT_M300_ST",
"GNT_C1105",
"GNT_C1105C",
"GNT_C1105R",
"GNT_C1105U",
"hilux1_civil_1_open",
"hilux1_civil_2_covered",
"hilux1_civil_3_open_EP1",
"HMMWV_Ambulance",
"HMMWV_Ambulance_CZ_DES_EP1",
"HMMWV_DES_EP1",
"HMMWV_DZ",
"HMMWV_M1035_DES_EP1",
"HMMWV_M1151_M2_CZ_DES_EP1_DZ",
"HMMWV_M9910A2_SOV_DES_EP1_DZ",
"Ikarus",
"Ikarus_TK_CIV_EP1",
"JetSkiYanahui_Case_Blue",
"JetSkiYanahui_Case_Green",
"JetSkiYanahui_Case_Red",
"JetSkiYanahui_Case_Yellow",
"Kamaz",
"KamazRefuel_DZ",
"Lada1",
"Lada1_TK_CIV_EP1",
"Lada2",
"Lada2_TK_CIV_EP1",
"LadaLM",
"LandRover_CZ_EP1",
"LandRover_MG_TK_EP1_DZ",
"LandRover_Special_CZ_EP1_DZ",
"LandRover_TK_CIV_EP1",
"MMT_Civ",
"MtvrRefuel_DES_EP1_DZ",
"MTVR_DES_EP1",
"Offroad_DSHKM_Gue_DZ",
"PBX",
"Pickup_PK_GUE_DZ",
"Pickup_PK_INS_DZ",
"Pickup_PK_TK_GUE_EP1_DZ",
"RHIB",
"S1203_ambulance_EP1",
"S1203_TK_CIV_EP1",
"Skoda",
"SkodaBlue",
"SkodaGreen",
"SkodaRed",
"Smallboat_1",
"Smallboat_2",
"SUV_Blue",
"SUV_Camo",
"SUV_Charcoal",
"SUV_Green",
"SUV_Orange",
"SUV_Pink",
"SUV_Red",
"SUV_Silver",
"SUV_TK_CIV_EP1",
"SUV_White",
"SUV_Yellow",
"tractor",
"TT650_Civ",
"TT650_Ins",
"TT650_TK_CIV_EP1",
"UAZ_CDF",
"UAZ_INS",
"UAZ_MG_TK_EP1_DZ",
"UAZ_RU",
"UAZ_Unarmed_TK_CIV_EP1",
"UAZ_Unarmed_TK_EP1",
"UAZ_Unarmed_UN_EP1",
"UralRefuel_TK_EP1_DZ",
"Ural_CDF",
"Ural_TK_CIV_EP1",
"Ural_UN_EP1",
"V3S_Open_TK_CIV_EP1",
"V3S_Open_TK_EP1",
"V3S_Refuel_TK_GUE_EP1_DZ",
"VolhaLimo_TK_CIV_EP1",
"Volha_1_TK_CIV_EP1",
"Volha_2_TK_CIV_EP1",
"VWGolf",
"V3S_Civ",
"V3S_TK_EP1_DZE",
"V3S_RA_TK_GUE_EP1_DZE",
"UralCivil_DZE",
"UralCivil2_DZE",
"KamazOpen_DZE",
"MtvrRefuel_DZ",
"MTVR",
"Zodiac",
	"2s6m_tunguska",
	"aav",
	"armoredsuv_pmc",
	"armoredsuv_pmc_dz",
	"armoredsuv_pmc_dze",
	"atv_cz_ep1",
	"atv_us_ep1",
	"av8b",
	"av8b2",
	"baf_atv_d",
	"baf_atv_w",
	"baf_fv510_d",
	"baf_fv510_w",
	"baf_jackal2_gmg_d",
	"baf_jackal2_gmg_w",
	"baf_jackal2_l2a1_d",
	"baf_jackal2_l2a1_w",
	"baf_merlin_dze",
	"baf_offroad_d",
	"baf_offroad_w",
	"bmp2_ambul_cdf",
	"bmp2_ambul_ins",
	"bmp2_cdf",
	"bmp2_gue",
	"bmp2_hq_cdf",
	"bmp2_hq_ins",
	"bmp2_hq_tk_ep1",
	"bmp2_ins",
	"bmp2_tk_ep1",
	"bmp2_un_ep1",
	"bmp3",
	"brdm2_atgm_cdf",
	"brdm2_atgm_ins",
	"brdm2_atgm_tk_ep1",
	"brdm2_atgm_tk_gue_ep1",
	"brdm2_cdf",
	"brdm2_gue",
	"brdm2_hq_gue",
	"brdm2_hq_tk_gue_ep1",
	"brdm2_ins",
	"brdm2_tk_ep1",
	"brdm2_tk_gue_ep1",
	"btr40_mg_tk_gue_ep1",
	"btr40_mg_tk_ins_ep1",
	"btr40_tk_gue_ep1",
	"btr40_tk_ins_ep1",
	"btr60_tk_ep1",
	"btr90",
	"btr90_hq",
	"car_hatchback",
	"car_sedan",
	"chukar",
	"chukar_ep1",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open",
	"fishing_boat",
	"gaz_vodnik",
	"gaz_vodnik_dz",
	"gaz_vodnik_dz_lm",
	"gaz_vodnik_dz_vlm",
	"gaz_vodnik_dze",
	"gaz_vodnik_hmg",
	"gaz_vodnik_medevac",
	"glt_m300_lt",
	"glt_m300_st",
	"gnt_c185",
	"gnt_c185c",
	"gnt_c185e",
	"gnt_c185f",
	"gnt_c185r",
	"gnt_c185t",
	"gnt_c185u",
	"grad_cdf",
	"grad_ins",
	"grad_ru",
	"grad_tk_ep1",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open",
	"hilux1_civil_3_open_ep1",
	"hmmwv",
	"hmmwv_ambulance",
	"hmmwv_ambulance_cz_des_ep1",
	"hmmwv_ambulance_des_ep1",
	"hmmwv_armored",
	"hmmwv_avenger",
	"hmmwv_avenger_des_ep1",
	"hmmwv_des_ep1",
	"hmmwv_dz",
	"hmmwv_m1035_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1_dz",
	"hmmwv_m1151_m2_cz_des_ep1_dze",
	"hmmwv_m1151_m2_des_ep1",
	"hmmwv_m2",
	"hmmwv_m998_crows_m2_des_ep1",
	"hmmwv_m998_crows_mk19_des_ep1",
	"hmmwv_m998a2_sov_des_ep1",
	"hmmwv_m998a2_sov_des_ep1_dz",
	"hmmwv_m998a2_sov_des_ep1_dze",
	"hmmwv_mk19",
	"hmmwv_mk19_des_ep1",
	"hmmwv_terminal_ep1",
	"hmmwv_tow",
	"hmmwv_tow_des_ep1",
	"ikarus",
	"ikarus_tk_civ_ep1",
	"jetskiyanahui_blue",
	"jetskiyanahui_green",
	"jetskiyanahui_red",
	"jetskiyanahui_yellow",
	"kamaz",
	"kamazopen",
	"kamazreammo",
	"kamazrefuel",
	"kamazrefuel_dz",
	"kamazrepair",
	"lada1",
	"lada1_gdr",
	"lada1_tk_civ_ep1",
	"lada2",
	"lada2_gdr",
	"lada2_tk_civ_ep1",
	"lada4_gdr",
	"lada5_gdr",
	"lada_base",
	"ladalm",
	"landrover_cz_ep1",
	"landrover_mg_tk_ep1",
	"landrover_mg_tk_ep1_dz",
	"landrover_mg_tk_ep1_dze",
	"landrover_mg_tk_ins_ep1",
	"landrover_special_cz_ep1",
	"landrover_special_cz_ep1_dz",
	"landrover_special_cz_ep1_dze",
	"landrover_spg9_tk_ep1",
	"landrover_spg9_tk_ins_ep1",
	"landrover_tk_civ_ep1",
	"lav25",
	"lav25_hq",
	"m1030",
	"m1030_us_des_ep1",
	"m1126_icv_m2_ep1",
	"m1126_icv_mk19_ep1",
	"m1128_mgs_ep1",
	"m1129_mc_ep1",
	"m1130_cv_ep1",
	"m1133_mev_ep1",
	"m1135_atgmv_ep1",
	"m113_tk_ep1",
	"m113_un_ep1",
	"m113ambul_tk_ep1",
	"m113ambul_tk_ep1_dz",
	"m113ambul_un_ep1",
	"m113ambul_un_ep1_dz",
	"m1a1",
	"m1a1_us_des_ep1",
	"m1a2_tusk_mg",
	"m1a2_us_tusk_mg_ep1",
	"m2a2_ep1",
	"m2a3_ep1",
	"m6_ep1",
	"maz_543_scud_tk_ep1",
	"mlrs",
	"mlrs_des_ep1",
	"mmt_civ",
	"mmt_usmc",
	"mq9predatorb_us_ep1",
	"mtvr",
	"mtvr_des_ep1",
	"mtvrreammo",
	"mtvrreammo_des_ep1",
	"mtvrrefuel",
	"mtvrrefuel_des_ep1",
	"mtvrrefuel_des_ep1_dz",
	"mtvrrepair",
	"mtvrrepair_des_ep1",
	"mtvrsalvage_des_ep1",
	"mtvrsupply_des_ep1",
	"offroad_dshkm_gue",
	"offroad_dshkm_gue_dz",
	"offroad_dshkm_gue_dze",
	"offroad_dshkm_gue_dze1",
	"offroad_dshkm_gue_dze2",
	"offroad_dshkm_gue_dze3",
	"offroad_dshkm_gue_dze4",
	"offroad_dshkm_ins",
	"offroad_dshkm_tk_gue_ep1",
	"offroad_spg9_gue",
	"offroad_spg9_tk_gue_ep1",
	"old_bike_tk_civ_ep1",
	"old_bike_tk_ins_ep1",
	"old_moto_tk_civ_ep1",
	"papercar",
	"pbx",
	"pchela1t",
	"pickup_pk_gue",
	"pickup_pk_gue_dz",
	"pickup_pk_gue_dze",
	"pickup_pk_ins",
	"pickup_pk_ins_dz",
	"pickup_pk_ins_dze",
	"pickup_pk_tk_gue_ep1",
	"pickup_pk_tk_gue_ep1_dz",
	"pickup_pk_tk_gue_ep1_dze",
	"policecar",
	"rhib",
	"rhib2turret",
	"s1203_ambulance_ep1",
	"s1203_tk_civ_ep1",
	"seafox",
	"seafox_ep1",
	"skoda",
	"skodablue",
	"skodagreen",
	"skodared",
	"smallboat_1",
	"smallboat_2",
	"suv_blue",
	"suv_camo",
	"suv_charcoal",
	"suv_dz",
	"suv_green",
	"suv_orange",
	"suv_pink",
	"suv_pmc",
	"suv_pmc_baf",
	"suv_red",
	"suv_silver",
	"suv_tk_civ_ep1",
	"suv_tk_ep1",
	"suv_un_ep1",
	"suv_white",
	"suv_yellow",
	"t34",
	"t34_tk_ep1",
	"t34_tk_gue_ep1",
	"t55_tk_ep1",
	"t55_tk_gue_ep1",
	"t72_cdf",
	"t72_gue",
	"t72_ins",
	"t72_ru",
	"t72_tk_ep1",
	"t90",
	"towingtractor",
	"tractor",
	"tractorold",
	"tt650_civ",
	"tt650_gue",
	"tt650_ins",
	"tt650_tk_civ_ep1",
	"tt650_tk_ep1",
	"uaz_ags30_cdf",
	"uaz_ags30_ins",
	"uaz_ags30_ru",
	"uaz_ags30_tk_ep1",
	"uaz_cdf",
	"uaz_ins",
	"uaz_mg_cdf",
	"uaz_mg_cdf",
	"uaz_mg_cdf_dz_lm",
	"uaz_mg_cdf_dz_vlm",
	"uaz_mg_ins",
	"uaz_mg_ins_dz_lm",
	"uaz_mg_ins_dz_vlm",
	"uaz_mg_tk_ep1",
	"uaz_mg_tk_ep1_dz",
	"uaz_mg_tk_ep1_dze",
	"uaz_ru",
	"uaz_spg9_ins",
	"uaz_unarmed_tk_civ_ep1",
	"uaz_unarmed_tk_ep1",
	"uaz_unarmed_un_ep1",
	"ural_cdf",
	"ural_ins",
	"ural_tk_civ_ep1",
	"ural_un_ep1",
	"ural_zu23_cdf",
	"ural_zu23_gue",
	"ural_zu23_ins",
	"ural_zu23_tk_ep1",
	"ural_zu23_tk_gue_ep1",
	"uralcivil",
	"uralcivil2",
	"uralopen_cdf",
	"uralopen_ins",
	"uralreammo_cdf",
	"uralreammo_ins",
	"uralreammo_tk_ep1",
	"uralrefuel_cdf",
	"uralrefuel_ins",
	"uralrefuel_tk_ep1",
	"uralrefuel_tk_ep1_dz",
	"uralrepair_cdf",
	"uralrepair_ins",
	"uralrepair_tk_ep1",
	"uralsalvage_tk_ep1",
	"uralsupply_tk_ep1",
	"v3s_civ",
	"v3s_gue",
	"v3s_open_tk_civ_ep1",
	"v3s_open_tk_ep1",
	"v3s_reammo_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1_dz",
	"v3s_repair_tk_gue_ep1",
	"v3s_salvage_tk_gue_ep1",
	"v3s_supply_tk_gue_ep1",
	"v3s_tk_ep1",
	"v3s_tk_gue_ep1",
	"volha_1_tk_civ_ep1",
	"volha_2_tk_civ_ep1",
	"volhalimo_tk_civ_ep1",
	"vwgolf",
	"warfarereammotruck_cdf",
	"warfarereammotruck_gue",
	"warfarereammotruck_ins",
	"warfarereammotruck_ru",
	"warfarereammotruck_usmc",
	"warfarerepairtruck_gue",
	"warfaresalvagetruck_cdf",
	"warfaresalvagetruck_gue",
	"warfaresalvagetruck_ins",
	"warfaresalvagetruck_ru",
	"warfaresalvagetruck_usmc",
	"warfaresupplytruck_cdf",
	"warfaresupplytruck_gue",
	"warfaresupplytruck_ins",
	"warfaresupplytruck_ru",
	"warfaresupplytruck_usmc",
	"zodiac",
	"zsu_cdf",
	"zsu_ins",
	"zsu_tk_ep1"
];

/**
 * List of class names of towables objects.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_objets_remorquables = R3F_LOG_CFG_objets_remorquables +
[
	"M119",
	"D30_base",
	"ZU23_base",
"AN2_DZ",
"ArmoredSUV_PMC_DZ",
"ATV_CZ_EP1",
"ATV_US_EP1",
"C130J_US_EP1",
"car_hatchback",
"car_sedan",
"CSJ_GyroC",
"CSJ_GyroCover",
"CSJ_GyroP",
"datsun1_civil_1_open",
"datsun1_civil_2_covered",
"datsun1_civil_3_open",
"Fishing_Boat",
"GAZ_Vodnik_DZ",
"GAZ_Vodnik_MedEvac",
"GLT_M300_LT",
"GLT_M300_ST",
"GNT_C1105",
"GNT_C1105C",
"GNT_C1105R",
"GNT_C1105U",
"hilux1_civil_1_open",
"hilux1_civil_2_covered",
"hilux1_civil_3_open_EP1",
"HMMWV_Ambulance",
"HMMWV_Ambulance_CZ_DES_EP1",
"HMMWV_DES_EP1",
"HMMWV_DZ",
"HMMWV_M1035_DES_EP1",
"HMMWV_M1151_M2_CZ_DES_EP1_DZ",
"HMMWV_M9910A2_SOV_DES_EP1_DZ",
"Ikarus",
"Ikarus_TK_CIV_EP1",
"JetSkiYanahui_Case_Blue",
"JetSkiYanahui_Case_Green",
"JetSkiYanahui_Case_Red",
"JetSkiYanahui_Case_Yellow",
"Kamaz",
"KamazRefuel_DZ",
"Lada1",
"Lada1_TK_CIV_EP1",
"Lada2",
"Lada2_TK_CIV_EP1",
"LadaLM",
"LandRover_CZ_EP1",
"LandRover_MG_TK_EP1_DZ",
"LandRover_Special_CZ_EP1_DZ",
"LandRover_TK_CIV_EP1",
"M1030_US_DES_EP1",
"MMT_Civ",
"MtvrRefuel_DES_EP1_DZ",
"MTVR_DES_EP1",
"Offroad_DSHKM_Gue_DZ",
"Old_bike_TK_INS_EP1",
"Old_moto_TK_Civ_EP1",
"PBX",
"Pickup_PK_GUE_DZ",
"Pickup_PK_INS_DZ",
"Pickup_PK_TK_GUE_EP1_DZ",
"RHIB",
"S1203_ambulance_EP1",
"S1203_TK_CIV_EP1",
"Skoda",
"SkodaBlue",
"SkodaGreen",
"SkodaRed",
"Smallboat_1",
"Smallboat_2",
"SUV_Blue",
"SUV_Camo",
"SUV_Charcoal",
"SUV_Green",
"SUV_Orange",
"SUV_Pink",
"SUV_Red",
"SUV_Silver",
"SUV_TK_CIV_EP1",
"SUV_White",
"SUV_Yellow",
"tractor",
"TT650_Civ",
"TT650_Ins",
"TT650_TK_CIV_EP1",
"UAZ_CDF",
"UAZ_INS",
"UAZ_MG_TK_EP1_DZ",
"UAZ_RU",
"UAZ_Unarmed_TK_CIV_EP1",
"UAZ_Unarmed_TK_EP1",
"UAZ_Unarmed_UN_EP1",
"UralRefuel_TK_EP1_DZ",
"Ural_CDF",
"Ural_TK_CIV_EP1",
"Ural_UN_EP1",
"V3S_Open_TK_CIV_EP1",
"V3S_Open_TK_EP1",
"V3S_Refuel_TK_GUE_EP1_DZ",
"VolhaLimo_TK_CIV_EP1",
"Volha_1_TK_CIV_EP1",
"Volha_2_TK_CIV_EP1",
"VWGolf",
"V3S_Civ",
"V3S_TK_EP1_DZE",
"V3S_RA_TK_GUE_EP1_DZE",
"UralCivil_DZE",
"UralCivil2_DZE",
"KamazOpen_DZE",
"MtvrRefuel_DZ",
"MTVR",
"Zodiac",
	"2s6m_tunguska",
	"aav",
	"an2_1_tk_civ_ep1",
	"an2_2_tk_civ_ep1",
	"an2_dz",
	"an2_dz",
	"an2_tk_ep1",
	"armoredsuv_pmc",
	"armoredsuv_pmc_dz",
	"armoredsuv_pmc_dze",
	"atv_cz_ep1",
	"atv_us_ep1",
	"av8b",
	"av8b2",
	"baf_atv_d",
	"baf_atv_w",
	"baf_fv510_d",
	"baf_fv510_w",
	"baf_jackal2_gmg_d",
	"baf_jackal2_gmg_w",
	"baf_jackal2_l2a1_d",
	"baf_jackal2_l2a1_w",
	"baf_offroad_d",
	"baf_offroad_w",
	"bmp2_ambul_cdf",
	"bmp2_ambul_ins",
	"bmp2_cdf",
	"bmp2_gue",
	"bmp2_hq_cdf",
	"bmp2_hq_ins",
	"bmp2_hq_tk_ep1",
	"bmp2_ins",
	"bmp2_tk_ep1",
	"bmp2_un_ep1",
	"bmp3",
	"brdm2_atgm_cdf",
	"brdm2_atgm_ins",
	"brdm2_atgm_tk_ep1",
	"brdm2_atgm_tk_gue_ep1",
	"brdm2_cdf",
	"brdm2_gue",
	"brdm2_hq_gue",
	"brdm2_hq_tk_gue_ep1",
	"brdm2_ins",
	"brdm2_tk_ep1",
	"brdm2_tk_gue_ep1",
	"btr40_mg_tk_gue_ep1",
	"btr40_mg_tk_ins_ep1",
	"btr40_tk_gue_ep1",
	"btr40_tk_ins_ep1",
	"btr60_tk_ep1",
	"btr90",
	"btr90_hq",
	"c130j",
	"c130j_us_ep1",
	"c130j_us_ep1_dz",
	"car_hatchback",
	"car_sedan",
	"chukar",
	"chukar_ep1",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open",
	"fishing_boat",
	"gaz_vodnik",
	"gaz_vodnik_dz",
	"gaz_vodnik_dz_lm",
	"gaz_vodnik_dz_vlm",
	"gaz_vodnik_dze",
	"gaz_vodnik_hmg",
	"gaz_vodnik_medevac",
	"glt_m300_lt",
	"glt_m300_st",
	"gnt_c185",
	"gnt_c185c",
	"gnt_c185e",
	"gnt_c185f",
	"gnt_c185r",
	"gnt_c185t",
	"gnt_c185u",
	"grad_cdf",
	"grad_ins",
	"grad_ru",
	"grad_tk_ep1",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open",
	"hilux1_civil_3_open_ep1",
	"hmmwv",
	"hmmwv_ambulance",
	"hmmwv_ambulance_cz_des_ep1",
	"hmmwv_ambulance_des_ep1",
	"hmmwv_armored",
	"hmmwv_avenger",
	"hmmwv_avenger_des_ep1",
	"hmmwv_des_ep1",
	"hmmwv_dz",
	"hmmwv_m1035_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1_dz",
	"hmmwv_m1151_m2_cz_des_ep1_dze",
	"hmmwv_m1151_m2_des_ep1",
	"hmmwv_m2",
	"hmmwv_m998_crows_m2_des_ep1",
	"hmmwv_m998_crows_mk19_des_ep1",
	"hmmwv_m998a2_sov_des_ep1",
	"hmmwv_m998a2_sov_des_ep1_dz",
	"hmmwv_m998a2_sov_des_ep1_dze",
	"hmmwv_mk19",
	"hmmwv_mk19_des_ep1",
	"hmmwv_terminal_ep1",
	"hmmwv_tow",
	"hmmwv_tow_des_ep1",
	"ikarus",
	"ikarus_tk_civ_ep1",
	"jetskiyanahui_blue",
	"jetskiyanahui_green",
	"jetskiyanahui_red",
	"jetskiyanahui_yellow",
	"kamaz",
	"kamazopen",
	"kamazreammo",
	"kamazrefuel",
	"kamazrefuel_dz",
	"kamazrepair",
	"lada1",
	"lada1_gdr",
	"lada1_tk_civ_ep1",
	"lada2",
	"lada2_gdr",
	"lada2_tk_civ_ep1",
	"lada4_gdr",
	"lada5_gdr",
	"lada_base",
	"ladalm",
	"landrover_cz_ep1",
	"landrover_mg_tk_ep1",
	"landrover_mg_tk_ep1_dz",
	"landrover_mg_tk_ep1_dze",
	"landrover_mg_tk_ins_ep1",
	"landrover_special_cz_ep1",
	"landrover_special_cz_ep1_dz",
	"landrover_special_cz_ep1_dze",
	"landrover_spg9_tk_ep1",
	"landrover_spg9_tk_ins_ep1",
	"landrover_tk_civ_ep1",
	"lav25",
	"lav25_hq",
	"m1030",
	"m1030_us_des_ep1",
	"m1126_icv_m2_ep1",
	"m1126_icv_mk19_ep1",
	"m1128_mgs_ep1",
	"m1129_mc_ep1",
	"m1130_cv_ep1",
	"m1133_mev_ep1",
	"m1135_atgmv_ep1",
	"m113_tk_ep1",
	"m113_un_ep1",
	"m113ambul_tk_ep1",
	"m113ambul_tk_ep1_dz",
	"m113ambul_un_ep1",
	"m113ambul_un_ep1_dz",
	"m1a1",
	"m1a1_us_des_ep1",
	"m1a2_tusk_mg",
	"m1a2_us_tusk_mg_ep1",
	"m2a2_ep1",
	"m2a3_ep1",
	"m6_ep1",
	"maz_543_scud_tk_ep1",
	"mlrs",
	"mlrs_des_ep1",
	"mmt_civ",
	"mmt_usmc",
	"mq9predatorb_us_ep1",
	"mtvr",
	"mtvr_des_ep1",
	"mtvrreammo",
	"mtvrreammo_des_ep1",
	"mtvrrefuel",
	"mtvrrefuel_des_ep1",
	"mtvrrefuel_des_ep1_dz",
	"mtvrrepair",
	"mtvrrepair_des_ep1",
	"mtvrsalvage_des_ep1",
	"mtvrsupply_des_ep1",
	"offroad_dshkm_gue",
	"offroad_dshkm_gue_dz",
	"offroad_dshkm_gue_dze",
	"offroad_dshkm_gue_dze1",
	"offroad_dshkm_gue_dze2",
	"offroad_dshkm_gue_dze3",
	"offroad_dshkm_gue_dze4",
	"offroad_dshkm_ins",
	"offroad_dshkm_tk_gue_ep1",
	"offroad_spg9_gue",
	"offroad_spg9_tk_gue_ep1",
	"old_bike_tk_civ_ep1",
	"old_bike_tk_ins_ep1",
	"old_moto_tk_civ_ep1",
	"papercar",
	"pbx",
	"pchela1t",
	"pickup_pk_gue",
	"pickup_pk_gue_dz",
	"pickup_pk_gue_dze",
	"pickup_pk_ins",
	"pickup_pk_ins_dz",
	"pickup_pk_ins_dze",
	"pickup_pk_tk_gue_ep1",
	"pickup_pk_tk_gue_ep1_dz",
	"pickup_pk_tk_gue_ep1_dze",
	"policecar",
	"rhib",
	"rhib2turret",
	"s1203_ambulance_ep1",
	"s1203_tk_civ_ep1",
	"seafox",
	"seafox_ep1",
	"skoda",
	"skodablue",
	"skodagreen",
	"skodared",
	"smallboat_1",
	"smallboat_2",
	"suv_blue",
	"suv_camo",
	"suv_charcoal",
	"suv_dz",
	"suv_green",
	"suv_orange",
	"suv_pink",
	"suv_pmc",
	"suv_pmc_baf",
	"suv_red",
	"suv_silver",
	"suv_tk_civ_ep1",
	"suv_tk_ep1",
	"suv_un_ep1",
	"suv_white",
	"suv_yellow",
	"t34",
	"t34_tk_ep1",
	"t34_tk_gue_ep1",
	"t55_tk_ep1",
	"t55_tk_gue_ep1",
	"t72_cdf",
	"t72_gue",
	"t72_ins",
	"t72_ru",
	"t72_tk_ep1",
	"t90",
	"towingtractor",
	"tractor",
	"tractorold",
	"tt650_civ",
	"tt650_gue",
	"tt650_ins",
	"tt650_tk_civ_ep1",
	"tt650_tk_ep1",
	"uaz_ags30_cdf",
	"uaz_ags30_ins",
	"uaz_ags30_ru",
	"uaz_ags30_tk_ep1",
	"uaz_cdf",
	"uaz_ins",
	"uaz_mg_cdf",
	"uaz_mg_cdf",
	"uaz_mg_cdf_dz_lm",
	"uaz_mg_cdf_dz_vlm",
	"uaz_mg_ins",
	"uaz_mg_ins_dz_lm",
	"uaz_mg_ins_dz_vlm",
	"uaz_mg_tk_ep1",
	"uaz_mg_tk_ep1_dz",
	"uaz_mg_tk_ep1_dze",
	"uaz_ru",
	"uaz_spg9_ins",
	"uaz_unarmed_tk_civ_ep1",
	"uaz_unarmed_tk_ep1",
	"uaz_unarmed_un_ep1",
	"ural_cdf",
	"ural_ins",
	"ural_tk_civ_ep1",
	"ural_un_ep1",
	"ural_zu23_cdf",
	"ural_zu23_gue",
	"ural_zu23_ins",
	"ural_zu23_tk_ep1",
	"ural_zu23_tk_gue_ep1",
	"uralcivil",
	"uralcivil2",
	"uralopen_cdf",
	"uralopen_ins",
	"uralreammo_cdf",
	"uralreammo_ins",
	"uralreammo_tk_ep1",
	"uralrefuel_cdf",
	"uralrefuel_ins",
	"uralrefuel_tk_ep1",
	"uralrefuel_tk_ep1_dz",
	"uralrepair_cdf",
	"uralrepair_ins",
	"uralrepair_tk_ep1",
	"uralsalvage_tk_ep1",
	"uralsupply_tk_ep1",
	"v3s_civ",
	"v3s_gue",
	"v3s_open_tk_civ_ep1",
	"v3s_open_tk_ep1",
	"v3s_reammo_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1_dz",
	"v3s_repair_tk_gue_ep1",
	"v3s_salvage_tk_gue_ep1",
	"v3s_supply_tk_gue_ep1",
	"v3s_tk_ep1",
	"v3s_tk_gue_ep1",
	"volha_1_tk_civ_ep1",
	"volha_2_tk_civ_ep1",
	"volhalimo_tk_civ_ep1",
	"vwgolf",
	"warfarereammotruck_cdf",
	"warfarereammotruck_gue",
	"warfarereammotruck_ins",
	"warfarereammotruck_ru",
	"warfarereammotruck_usmc",
	"warfarerepairtruck_gue",
	"warfaresalvagetruck_cdf",
	"warfaresalvagetruck_gue",
	"warfaresalvagetruck_ins",
	"warfaresalvagetruck_ru",
	"warfaresalvagetruck_usmc",
	"warfaresupplytruck_cdf",
	"warfaresupplytruck_gue",
	"warfaresupplytruck_ins",
	"warfaresupplytruck_ru",
	"warfaresupplytruck_usmc",
	"zodiac",
	"zsu_cdf",
	"zsu_ins",
	"zsu_tk_ep1"
];


/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of air vehicles which can lift liftable objects.
 * Liste des noms de classes des véhicules aériens pouvant héliporter des objets héliportables.
 */
R3F_LOG_CFG_heliporteurs = R3F_LOG_CFG_heliporteurs +
[
	"CH47_base_EP1",
	"Mi17_base",
	"Mi24_Base",
	"UH1H_base",
	"UH1_Base",
	"UH60_Base",
	"MV22",
"CH47_base_EP1",
	"Mi17_base",
	"Mi24_Base",
	"UH1H_base",
	"UH1_Base",
	"UH60_Base",
	"MV22",
	"CH_47F_EP1_DZ",
	"MH6J_DZ",
	"Mi17_Civilian_DZ",
	"Mi17_DZ",
	"MV22_DZ",
	"UH1H_DZ",
    "UH1Y_DZ",
	"BAF_Merlin_HC3_D",
    "UH60M_EP1_DZ",
	"a10",
	"a10_us_ep1",
	"ah64d_ep1",
	"ah6j_ep1",
	"ah6x_dz",
	"an2_1_tk_civ_ep1",
	"an2_2_tk_civ_ep1",
	"an2_dz",
	"an2_tk_ep1",
	"baf_merlin_dze",
	"c130j",
	"c130j_us_ep1",
	"c130j_us_ep1_dz",
	"ch53_dze",
	"ch_47f_baf",
	"ch_47f_ep1",
	"ch_47f_ep1_dz",
	"ch_47f_ep1_dze",
	"csj_gyroc",
	"csj_gyrocover",
	"csj_gyrop",
	"f35b",
	"l39_tk_ep1",
	"m6_ep1",
	"mh6j_dz",
	"mi17_civilian_dz",
	"mi17_dze",
	"mq9predatorb_us_ep1",
	"mv22_dz",
	"su25_cdf",
	"su25_ins",
	"su25_tk_ep1",
	"su34",
	"su39",
	"uh1h_dze",
	"uh1h_tk_ep1",
	"uh1y",
	"uh1y_dze",
	"uh60m_ep1_dze"
];

/**
 * List of class names of liftable objects.
 * Liste des noms de classes des objets héliportables.
 */
R3F_LOG_CFG_objets_heliportables = R3F_LOG_CFG_objets_heliportables +
[
	"ReammoBox",
	"ATV_Base_EP1",
	"HMMWV_Base",
	"Ikarus_TK_CIV_EP1",
	"Lada_base",
	"LandRover_Base",
	"Offroad_DSHKM_base",
	"Pickup_PK_base",
	"S1203_TK_CIV_EP1",
	"SUV_Base_EP1",
	"SkodaBase",
	"TowingTractor",
	"Tractor",
	"Kamaz_Base",
	"MTVR",
	"GRAD_Base",
	"Ural_Base",
	"Ural_ZU23_Base",
	"V3S_Base",
	"UAZ_Base",
	"VWGolf",
	"Volha_TK_CIV_Base_EP1",
	"BTR40_MG_base_EP1",
	"hilux1_civil_1_open",
	"hilux1_civil_3_open_EP1",
	"D30_base",
	"M119",
	"ZU23_base",
	"Boat",
	"Fishing_Boat",
	"SeaFox",
	"Smallboat_1",
	"Land_Misc_Cargo1A_EP1",
	"Land_Misc_Cargo1B",
	"Land_Misc_Cargo1B_EP1",
	"Land_Misc_Cargo1C",
	"Land_Misc_Cargo1C_EP1",
	"Land_Misc_Cargo1D",
	"Land_Misc_Cargo1D_EP1",
	"Land_Misc_Cargo1E",
	"Land_Misc_Cargo1E_EP1",
	"Land_Misc_Cargo1F",
	"Land_Misc_Cargo1G",
	"Land_Misc_Cargo2A_EP1",
	"Land_Misc_Cargo2B",
	"Land_Misc_Cargo2B_EP1",
	"Land_Misc_Cargo2C",
	"Land_Misc_Cargo2C_EP1",
	"Land_Misc_Cargo2D",
	"Land_Misc_Cargo2D_EP1",
	"Land_Misc_Cargo2E",
	"Land_Misc_Cargo2E_EP1",
	"Base_WarfareBContructionSite",
	"Misc_cargo_cont_net1",
	"Misc_cargo_cont_net2",
	"Misc_cargo_cont_net3",
	"Misc_cargo_cont_small",
	"Misc_cargo_cont_small2",
	"Misc_cargo_cont_tiny",
"ATV_Base_EP1",
"HMMWV_Base",
"Ikarus_TK_CIV_EP1",
"Lada_base",
"LandRover_Base",
"Offroad_DSHKM_base",
"Pickup_PK_base",
"S1203_TK_CIV_EP1",
"SUV_Base_EP1",
"SkodaBase",
"TowingTractor",
"Tractor",
"Kamaz_Base",
"MTVR",
"GRAD_Base",
"Ural_Base",
"Ural_ZU23_Base",
"V3S_Base",
"UAZ_Base",
"VWGolf",
"Volha_TK_CIV_Base_EP1",
"BTR40_MG_base_EP1",
"hilux1_civil_1_open",
"hilux1_civil_3_open_EP1",
"D30_base",
"M119",
"ZU23_base",
"Boat",
"Fishing_Boat",
"SeaFox",
"Smallboat_1",
"ArmoredSUV_PMC_DZ",
"ATV_CZ_EP1",
"ATV_US_EP1",
"car_hatchback",
"car_sedan",
"datsun1_civil_1_open",
"datsun1_civil_2_covered",
"datsun1_civil_3_open",
"Fishing_Boat",
"GAZ_Vodnik_DZ",
"GAZ_Vodnik_MedEvac",
"GLT_M300_LT",
"GLT_M300_ST",
"GNT_C1105",
"GNT_C1105C",
"GNT_C1105R",
"GNT_C1105U",
"hilux1_civil_1_open",
"hilux1_civil_2_covered",
"hilux1_civil_3_open_EP1",
"HMMWV_Ambulance",
"HMMWV_Ambulance_CZ_DES_EP1",
"HMMWV_DES_EP1",
"HMMWV_DZ",
"HMMWV_M1035_DES_EP1",
"HMMWV_M1151_M2_CZ_DES_EP1_DZ",
"HMMWV_M9910A2_SOV_DES_EP1_DZ",
"Ikarus",
"Ikarus_TK_CIV_EP1",
"JetSkiYanahui_Case_Blue",
"JetSkiYanahui_Case_Green",
"JetSkiYanahui_Case_Red",
"JetSkiYanahui_Case_Yellow",
"Kamaz",
"KamazRefuel_DZ",
"Lada1",
"Lada1_TK_CIV_EP1",
"Lada2",
"Lada2_TK_CIV_EP1",
"LadaLM",
"LandRover_CZ_EP1",
"LandRover_MG_TK_EP1_DZ",
"LandRover_Special_CZ_EP1_DZ",
"LandRover_TK_CIV_EP1",
"MtvrRefuel_DES_EP1_DZ",
"MTVR_DES_EP1",
"Offroad_DSHKM_Gue_DZ",
"Old_moto_TK_Civ_EP1",
"PBX",
"Pickup_PK_GUE_DZ",
"Pickup_PK_INS_DZ",
"Pickup_PK_TK_GUE_EP1_DZ",
"RHIB",
"S1203_ambulance_EP1",
"S1203_TK_CIV_EP1",
"Skoda",
"SkodaBlue",
"SkodaGreen",
"SkodaRed",
"Smallboat_1",
"Smallboat_2",
"SUV_Blue",
"SUV_Camo",
"SUV_Charcoal",
"SUV_Green",
"SUV_Orange",
"SUV_Pink",
"SUV_Red",
"SUV_Silver",
"SUV_TK_CIV_EP1",
"SUV_White",
"SUV_Yellow",
"tractor",
"UAZ_CDF",
"UAZ_INS",
"UAZ_MG_TK_EP1_DZ",
"UAZ_RU",
"UAZ_Unarmed_TK_CIV_EP1",
"UAZ_Unarmed_TK_EP1",
"UAZ_Unarmed_UN_EP1",
"UralRefuel_TK_EP1_DZ",
"Ural_CDF",
"Ural_TK_CIV_EP1",
"Ural_UN_EP1",
"V3S_Open_TK_CIV_EP1",
"V3S_Open_TK_EP1",
"V3S_Refuel_TK_GUE_EP1_DZ",
"VolhaLimo_TK_CIV_EP1",
"Volha_1_TK_CIV_EP1",
"Volha_2_TK_CIV_EP1",
"VWGolf",
"V3S_Civ",
"V3S_TK_EP1_DZE",
"V3S_RA_TK_GUE_EP1_DZE",
"UralCivil_DZE",
"UralCivil2_DZE",
"KamazOpen_DZE",
"MtvrRefuel_DZ",
"MTVR",
"Zodiac",
	"2s6m_tunguska",
	"a10",
	"a10_us_ep1",
	"aav",
	"ah64d_ep1",
	"ah6j_dz",
	"ah6j_ep1",
	"ah6j_ep1",
	"ah6x_dz",
	"ah6x_ep1",
	"an2_1_tk_civ_ep1",
	"an2_1_tk_civ_ep1",
	"an2_2_tk_civ_ep1",
	"an2_2_tk_civ_ep1",
	"an2_dz",
	"an2_dz",
	"an2_tk_ep1",
	"an2_tk_ep1",
	"armoredsuv_pmc",
	"armoredsuv_pmc_dz",
	"armoredsuv_pmc_dze",
	"atv_cz_ep1",
	"atv_us_ep1",
	"av8b",
	"av8b2",
	"baf_atv_d",
	"baf_atv_w",
	"baf_fv510_d",
	"baf_fv510_w",
	"baf_jackal2_gmg_d",
	"baf_jackal2_gmg_w",
	"baf_jackal2_l2a1_d",
	"baf_jackal2_l2a1_w",
	"baf_merlin_dze",
	"baf_offroad_d",
	"baf_offroad_w",
	"bmp2_ambul_cdf",
	"bmp2_ambul_ins",
	"bmp2_cdf",
	"bmp2_gue",
	"bmp2_hq_cdf",
	"bmp2_hq_ins",
	"bmp2_hq_tk_ep1",
	"bmp2_ins",
	"bmp2_tk_ep1",
	"bmp2_un_ep1",
	"bmp3",
	"brdm2_atgm_cdf",
	"brdm2_atgm_ins",
	"brdm2_atgm_tk_ep1",
	"brdm2_atgm_tk_gue_ep1",
	"brdm2_cdf",
	"brdm2_gue",
	"brdm2_hq_gue",
	"brdm2_hq_tk_gue_ep1",
	"brdm2_ins",
	"brdm2_tk_ep1",
	"brdm2_tk_gue_ep1",
	"btr40_mg_tk_gue_ep1",
	"btr40_mg_tk_ins_ep1",
	"btr40_tk_gue_ep1",
	"btr40_tk_ins_ep1",
	"btr60_tk_ep1",
	"btr90",
	"btr90_hq",
	"c130j",
	"c130j_us_ep1",
	"c130j_us_ep1",
	"c130j_us_ep1_dz",
	"car_hatchback",
	"car_sedan",
	"ch53_dze",
	"ch_47f_baf",
	"ch_47f_baf",
	"ch_47f_ep1",
	"ch_47f_ep1",
	"ch_47f_ep1_dz",
	"ch_47f_ep1_dze",
	"chukar",
	"chukar_ep1",
	"csj_gyroc",
	"csj_gyrocover",
	"csj_gyrop",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open",
	"f35b",
	"fishing_boat",
	"gaz_vodnik",
	"gaz_vodnik_dz",
	"gaz_vodnik_dz_lm",
	"gaz_vodnik_dz_vlm",
	"gaz_vodnik_dze",
	"gaz_vodnik_hmg",
	"gaz_vodnik_medevac",
	"glt_m300_lt",
	"glt_m300_st",
	"gnt_c185",
	"gnt_c185c",
	"gnt_c185e",
	"gnt_c185f",
	"gnt_c185r",
	"gnt_c185t",
	"gnt_c185u",
	"grad_cdf",
	"grad_ins",
	"grad_ru",
	"grad_tk_ep1",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open",
	"hilux1_civil_3_open_ep1",
	"hmmwv",
	"hmmwv_ambulance",
	"hmmwv_ambulance_cz_des_ep1",
	"hmmwv_ambulance_des_ep1",
	"hmmwv_armored",
	"hmmwv_avenger",
	"hmmwv_avenger_des_ep1",
	"hmmwv_des_ep1",
	"hmmwv_dz",
	"hmmwv_m1035_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1_dz",
	"hmmwv_m1151_m2_cz_des_ep1_dze",
	"hmmwv_m1151_m2_des_ep1",
	"hmmwv_m2",
	"hmmwv_m998_crows_m2_des_ep1",
	"hmmwv_m998_crows_mk19_des_ep1",
	"hmmwv_m998a2_sov_des_ep1",
	"hmmwv_m998a2_sov_des_ep1_dz",
	"hmmwv_m998a2_sov_des_ep1_dze",
	"hmmwv_mk19",
	"hmmwv_mk19_des_ep1",
	"hmmwv_terminal_ep1",
	"hmmwv_tow",
	"hmmwv_tow_des_ep1",
	"ikarus",
	"ikarus_tk_civ_ep1",
	"jetskiyanahui_blue",
	"jetskiyanahui_green",
	"jetskiyanahui_red",
	"jetskiyanahui_yellow",
	"kamaz",
	"kamazopen",
	"kamazreammo",
	"kamazrefuel",
	"kamazrefuel_dz",
	"kamazrepair",
	"l39_tk_ep1",
	"lada1",
	"lada1_gdr",
	"lada1_tk_civ_ep1",
	"lada2",
	"lada2_gdr",
	"lada2_tk_civ_ep1",
	"lada4_gdr",
	"lada5_gdr",
	"lada_base",
	"ladalm",
	"landrover_cz_ep1",
	"landrover_mg_tk_ep1",
	"landrover_mg_tk_ep1_dz",
	"landrover_mg_tk_ep1_dze",
	"landrover_mg_tk_ins_ep1",
	"landrover_special_cz_ep1",
	"landrover_special_cz_ep1_dz",
	"landrover_special_cz_ep1_dze",
	"landrover_spg9_tk_ep1",
	"landrover_spg9_tk_ins_ep1",
	"landrover_tk_civ_ep1",
	"lav25",
	"lav25_hq",
	"m1030",
	"m1030_us_des_ep1",
	"m1126_icv_m2_ep1",
	"m1126_icv_mk19_ep1",
	"m1128_mgs_ep1",
	"m1129_mc_ep1",
	"m1130_cv_ep1",
	"m1133_mev_ep1",
	"m1135_atgmv_ep1",
	"m113_tk_ep1",
	"m113_un_ep1",
	"m113ambul_tk_ep1",
	"m113ambul_tk_ep1_dz",
	"m113ambul_un_ep1",
	"m113ambul_un_ep1_dz",
	"m1a1",
	"m1a1_us_des_ep1",
	"m1a2_tusk_mg",
	"m1a2_us_tusk_mg_ep1",
	"m2a2_ep1",
	"m2a3_ep1",
	"m6_ep1",
	"maz_543_scud_tk_ep1",
	"mh6j_dz",
	"mh6j_ep1",
	"mi171sh_cz_ep1",
	"mi17_civilian_dz",
	"mi17_dze",
	"mi17_tk_ep1",
	"mi17_un_cdf_ep1",
	"mlrs",
	"mlrs_des_ep1",
	"mmt_civ",
	"mmt_usmc",
	"mq9predatorb_us_ep1",
	"mtvr",
	"mtvr_des_ep1",
	"mtvrreammo",
	"mtvrreammo_des_ep1",
	"mtvrrefuel",
	"mtvrrefuel_des_ep1",
	"mtvrrefuel_des_ep1_dz",
	"mtvrrepair",
	"mtvrrepair_des_ep1",
	"mtvrsalvage_des_ep1",
	"mtvrsupply_des_ep1",
	"mv22",
	"mv22_dz",
	"offroad_dshkm_gue",
	"offroad_dshkm_gue_dz",
	"offroad_dshkm_gue_dze",
	"offroad_dshkm_gue_dze1",
	"offroad_dshkm_gue_dze2",
	"offroad_dshkm_gue_dze3",
	"offroad_dshkm_gue_dze4",
	"offroad_dshkm_ins",
	"offroad_dshkm_tk_gue_ep1",
	"offroad_spg9_gue",
	"offroad_spg9_tk_gue_ep1",
	"old_bike_tk_civ_ep1",
	"old_bike_tk_ins_ep1",
	"old_moto_tk_civ_ep1",
	"papercar",
	"pbx",
	"pchela1t",
	"pickup_pk_gue",
	"pickup_pk_gue_dz",
	"pickup_pk_gue_dze",
	"pickup_pk_ins",
	"pickup_pk_ins_dz",
	"pickup_pk_ins_dze",
	"pickup_pk_tk_gue_ep1",
	"pickup_pk_tk_gue_ep1_dz",
	"pickup_pk_tk_gue_ep1_dze",
	"policecar",
	"rhib",
	"rhib2turret",
	"s1203_ambulance_ep1",
	"s1203_tk_civ_ep1",
	"seafox",
	"seafox_ep1",
	"skoda",
	"skodablue",
	"skodagreen",
	"skodared",
	"smallboat_1",
	"smallboat_2",
	"su25_cdf",
	"su25_ins",
	"su25_tk_ep1",
	"su34",
	"su39",
	"suv_blue",
	"suv_camo",
	"suv_charcoal",
	"suv_dz",
	"suv_green",
	"suv_orange",
	"suv_pink",
	"suv_pmc",
	"suv_pmc_baf",
	"suv_red",
	"suv_silver",
	"suv_tk_civ_ep1",
	"suv_tk_ep1",
	"suv_un_ep1",
	"suv_white",
	"suv_yellow",
	"t34",
	"t34_tk_ep1",
	"t34_tk_gue_ep1",
	"t55_tk_ep1",
	"t55_tk_gue_ep1",
	"t72_cdf",
	"t72_gue",
	"t72_ins",
	"t72_ru",
	"t72_tk_ep1",
	"t90",
	"towingtractor",
	"tractor",
	"tractorold",
	"tt650_civ",
	"tt650_gue",
	"tt650_ins",
	"tt650_tk_civ_ep1",
	"tt650_tk_ep1",
	"uaz_ags30_cdf",
	"uaz_ags30_ins",
	"uaz_ags30_ru",
	"uaz_ags30_tk_ep1",
	"uaz_cdf",
	"uaz_ins",
	"uaz_mg_cdf",
	"uaz_mg_cdf",
	"uaz_mg_cdf_dz_lm",
	"uaz_mg_cdf_dz_vlm",
	"uaz_mg_ins",
	"uaz_mg_ins_dz_lm",
	"uaz_mg_ins_dz_vlm",
	"uaz_mg_tk_ep1",
	"uaz_mg_tk_ep1_dz",
	"uaz_mg_tk_ep1_dze",
	"uaz_ru",
	"uaz_spg9_ins",
	"uaz_unarmed_tk_civ_ep1",
	"uaz_unarmed_tk_ep1",
	"uaz_unarmed_un_ep1",
	"uh1h",
	"uh1h_dze",
	"uh1h_tk_ep1",
	"uh1y",
	"uh1y_dze",
	"uh60m_ep1",
	"uh60m_ep1_dze",
	"ural_cdf",
	"ural_ins",
	"ural_tk_civ_ep1",
	"ural_un_ep1",
	"ural_zu23_cdf",
	"ural_zu23_gue",
	"ural_zu23_ins",
	"ural_zu23_tk_ep1",
	"ural_zu23_tk_gue_ep1",
	"uralcivil",
	"uralcivil2",
	"uralopen_cdf",
	"uralopen_ins",
	"uralreammo_cdf",
	"uralreammo_ins",
	"uralreammo_tk_ep1",
	"uralrefuel_cdf",
	"uralrefuel_ins",
	"uralrefuel_tk_ep1",
	"uralrefuel_tk_ep1_dz",
	"uralrepair_cdf",
	"uralrepair_ins",
	"uralrepair_tk_ep1",
	"uralsalvage_tk_ep1",
	"uralsupply_tk_ep1",
	"v3s_civ",
	"v3s_gue",
	"v3s_open_tk_civ_ep1",
	"v3s_open_tk_ep1",
	"v3s_reammo_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1_dz",
	"v3s_repair_tk_gue_ep1",
	"v3s_salvage_tk_gue_ep1",
	"v3s_supply_tk_gue_ep1",
	"v3s_tk_ep1",
	"v3s_tk_gue_ep1",
	"volha_1_tk_civ_ep1",
	"volha_2_tk_civ_ep1",
	"volhalimo_tk_civ_ep1",
	"vwgolf",
	"warfarereammotruck_cdf",
	"warfarereammotruck_gue",
	"warfarereammotruck_ins",
	"warfarereammotruck_ru",
	"warfarereammotruck_usmc",
	"warfarerepairtruck_gue",
	"warfaresalvagetruck_cdf",
	"warfaresalvagetruck_gue",
	"warfaresalvagetruck_ins",
	"warfaresalvagetruck_ru",
	"warfaresalvagetruck_usmc",
	"warfaresupplytruck_cdf",
	"warfaresupplytruck_gue",
	"warfaresupplytruck_ins",
	"warfaresupplytruck_ru",
	"warfaresupplytruck_usmc",
	"zodiac",
	"zsu_cdf",
	"zsu_ins",
	"zsu_tk_ep1"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/

/*
 * This section use a quantification of the volume and/or weight of the objets.
 * The arbitrary referencial used is : an ammo box of type USSpecialWeaponsBox "weights" 5 units.
 * 
 * Cette section utilise une quantification du volume et/ou poids des objets.
 * Le référentiel arbitraire utilisé est : une caisse de munition de type USSpecialWeaponsBox "pèse" 5 unités.
 * 
 * Note : the priority of a declaration of capacity to another corresponds to their order in the tables.
 *   For example : the "Truck" class is in the "Car" class (see http://community.bistudio.com/wiki/ArmA_2:_CfgVehicles).
 *   If "Truck" is declared with a capacity of 140 before "Car". And if "Car" is declared after "Truck" with a capacity of 40,
 *   Then all the sub-classes in "Truck" will have a capacity of 140. And all the sub-classes of "Car", excepted the ones
 *   in "Truck", will have a capacity of 40.
 * 
 * Note : la priorité d'une déclaration de capacité sur une autre correspond à leur ordre dans les tableaux.
 *   Par exemple : la classe "Truck" appartient à la classe "Car" (voir http://community.bistudio.com/wiki/ArmA_2:_CfgVehicles).
 *   Si "Truck" est déclaré avec une capacité de 140 avant "Car". Et que "Car" est déclaré après "Truck" avec une capacité de 40,
 *   Alors toutes les sous-classes appartenant à "Truck" auront une capacité de 140. Et toutes les sous-classes appartenant
 *   à "Car", exceptées celles de "Truck", auront une capacité de 40.
 */

/**
 * List of class names of (ground or air) vehicles which can transport transportable objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 * 
 * Liste des noms de classes des véhicules (terrestres ou aériens) pouvant transporter des objets transportables.
 * Le deuxième élément des tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
 */
R3F_LOG_CFG_transporteurs = R3F_LOG_CFG_transporteurs +
[
	["CH47_base_EP1", 80],
	["AH6_Base_EP1", 25],
	["Mi17_base", 60],
	["Mi24_Base", 50],
	["UH1H_base", 35],
	["UH1_Base", 30],
	["UH60_Base", 40],
	["An2_Base_EP1", 40],
	["C130J", 150],
	["MV22", 80],
	["ATV_Base_EP1", 5],
	["HMMWV_Avenger", 5],
	["HMMWV_M998A2_SOV_DES_EP1", 12],
	["HMMWV_Base", 18],
	["Ikarus", 50],
	["Lada_base", 10],
	["LandRover_Base", 15],
	["Offroad_DSHKM_base", 15],
	["Pickup_PK_base", 15],
	["S1203_TK_CIV_EP1", 20],
	["SUV_Base_EP1", 15],
	["SkodaBase", 10],
	["TowingTractor", 5],
	["Tractor", 5],
	["KamazRefuel", 10],
	["Kamaz", 50],
	["Kamaz_Base", 35],
	["MAZ_543_SCUD_Base_EP1", 10],
	["MtvrReammo", 35],
	["MtvrRepair", 35],
	["MtvrRefuel", 10],
	["MTVR", 50],
	["GRAD_Base", 10],
	["Ural_ZU23_Base", 12],
	["Ural_CDF", 50],
	["Ural_INS", 50],
	["UralRefuel_Base", 10],
	["Ural_Base", 35],
	["V3S_Refuel_TK_GUE_EP1", 10],
	["V3S_Civ", 35],
	["V3S_Base_EP1", 50],
	["UAZ_Base", 10],
	["VWGolf", 8],
	["Volha_TK_CIV_Base_EP1", 8],
	["BRDM2_Base", 15],
	["BTR40_MG_base_EP1", 15],
	["BTR90_Base", 25],
	["GAZ_Vodnik_HMG", 25],
	["LAV25_Base", 25],
	["StrykerBase_EP1", 25],
	["hilux1_civil_1_open", 12],
	["hilux1_civil_3_open_EP1", 12],
	["Motorcycle", 3],
	["2S6M_Tunguska", 10],
	["M113_Base", 12],
	["M1A1", 5],
	["M2A2_Base", 15],
	["MLRS", 8],
	["T34", 5],
	["T55_Base", 5],
	["T72_Base", 5],
	["T90", 5],
	["AAV", 12],
	["BMP2_Base", 7],
	["BMP3", 7],
	["ZSU_Base", 5],
	["RHIB", 10],
	["RubberBoat", 5],
	["Fishing_Boat", 10],
	["SeaFox", 5],
	["Smallboat_1", 8],
	["Fort_Crate_wood", 5],
	["Land_Misc_Cargo1A_EP1", 100],
	["Land_Misc_Cargo1B", 100],
	["Misc_Cargo1B_military", 100],
	["Land_Misc_Cargo1B_EP1", 100],
	["Land_Misc_Cargo1C", 100],
	["Land_Misc_Cargo1C_EP1", 100],
	["Land_Misc_Cargo1D", 100],
	["Land_Misc_Cargo1D_EP1", 100],
	["Land_Misc_Cargo1E", 100],
	["Land_Misc_Cargo1E_EP1", 100],
	["Land_Misc_Cargo1F", 100],
	["Land_Misc_Cargo1G", 100],
	["Land_Misc_Cargo2A_EP1", 200],
	["Land_Misc_Cargo2B", 200],
	["Land_Misc_Cargo2B_EP1", 200],
	["Land_Misc_Cargo2C", 200],
	["Land_Misc_Cargo2C_EP1", 200],
	["Land_Misc_Cargo2D", 200],
	["Land_Misc_Cargo2D_EP1", 200],
	["Land_Misc_Cargo2E", 200],
	["Land_Misc_Cargo2E_EP1", 200],
	["Base_WarfareBContructionSite", 100],
	["Misc_cargo_cont_net1", 18],
	["Misc_cargo_cont_net2", 36],
	["Misc_cargo_cont_net3", 60],
	["Misc_cargo_cont_small", 50],
	["Misc_cargo_cont_small2", 40],
	["Misc_cargo_cont_tiny", 35]
];

/**
 * List of class names of transportable objects.
 * The second element of the arrays is the cost capacity (in relation with the capacity of the vehicles).
 * 
 * Liste des noms de classes des objets transportables.
 * Le deuxième élément des tableaux est le coût de capacité (en relation avec la capacité des véhicules).
 */
R3F_LOG_CFG_objets_transportables = R3F_LOG_CFG_objets_transportables +
[
	["SatPhone", 1], // Needed for the R3F_ARTY module (arty HQ) (nécessaire pour le module R3F_ARTY (PC d'arti))
	["Pchela1T", 15],
	["ATV_Base_EP1", 20],
	["FoldChair_with_Cargo", 1],
	["MMT_base", 1],
	["Old_bike_base_EP1", 1],
	["M1030", 5],
	["Old_moto_base", 5],
	["TT650_Base", 5],
	["Igla_AA_pod_East", 7],
	["Stinger_Pod_base", 7],
	["Metis", 4],
	["SPG9_base", 4],
	["TOW_TriPod", 5],
	["TOW_TriPod_Base", 5],
	["AGS_base", 4],
	["MK19_TriPod", 4],
	["DSHKM_base", 4],
	["KORD_Base", 5],
	["M2StaticMG_base", 4],
	["WarfareBMGNest_M240_base", 10],
	["WarfareBMGNest_PK_Base", 10],
	["2b14_82mm", 4],
	["M252", 4],
	["Warfare2b14_82mm_Base", 4],
	["StaticSEARCHLight", 4],
	["FlagCarrierSmall", 1],
	["Fort_Crate_wood", 2],
	["Fort_RazorWire", 2],
	["Gunrack1", 3],
	["Base_WarfareBBarrier10xTall", 10],
	["Base_WarfareBBarrier10x", 7],
	["Base_WarfareBBarrier5x", 5],
	["Fort_EnvelopeBig", 1],
	["Fort_EnvelopeSmall", 1],
	["Land_A_tent", 2],
	["Land_Antenna", 4],
	["Land_Fire_barrel", 1],
	["Land_GuardShed", 3],
	["Land_Misc_Cargo1A_EP1", 110],
	["Land_Misc_Cargo1B", 110],
	["Misc_Cargo1B_military", 110],
	["Land_Misc_Cargo1B_EP1", 110],
	["Land_Misc_Cargo1C", 110],
	["Land_Misc_Cargo1C_EP1", 110],
	["Land_Misc_Cargo1D", 110],
	["Land_Misc_Cargo1D_EP1", 110],
	["Land_Misc_Cargo1E", 110],
	["Land_Misc_Cargo1E_EP1", 110],
	["Land_Misc_Cargo1F", 110],
	["Land_Misc_Cargo1G", 110],
	["Land_Misc_Cargo2A_EP1", 220],
	["Land_Misc_Cargo2B", 220],
	["Land_Misc_Cargo2B_EP1", 220],
	["Land_Misc_Cargo2C", 220],
	["Land_Misc_Cargo2C_EP1", 220],
	["Land_Misc_Cargo2D", 220],
	["Land_Misc_Cargo2D_EP1", 220],
	["Land_Misc_Cargo2E", 220],
	["Land_Misc_Cargo2E_EP1", 220],
	["Land_fort_bagfence_corner", 2],
	["Land_fort_bagfence_long", 2],
	["Land_fort_bagfence_round", 3],
	["Land_fortified_nest_small", 6],
	["Land_tent_east", 6],
	["Land_BagFenceCorner", 2],
	["Land_HBarrier_large", 3],
	["Land_Toilet", 3],
	["RoadBarrier_light", 2],
	["WarfareBunkerSign", 1],
	["Base_WarfareBContructionSite", 110],
	["ACamp", 3],
	["Camp", 5],
	["CampEast", 6],
	["MASH", 5],
	["FlagCarrier", 1],
	["FlagCarrierChecked", 1],
	["Hedgehog", 3],
	["AmmoCrate_NoInteractive_Base_EP1", 5],
	["Misc_cargo_cont_net1", 40],
	["Misc_cargo_cont_net2", 50],
	["Misc_cargo_cont_net3", 100],
	["Misc_cargo_cont_small", 55],
	["Misc_cargo_cont_small2", 50],
	["Misc_cargo_cont_tiny", 40],
	["RUVehicleBox", 12],
	["TKVehicleBox_EP1", 12],
	["USVehicleBox_EP1", 12],
	["USVehicleBox", 12],
	["ReammoBox", 5],
	["TargetE", 2],
	["TargetEpopup", 2],
	["TargetPopUpTarget", 2],
	["Desk", 1],
	["FoldChair", 1],
	["FoldTable", 1],
	["Land_Barrel_empty", 1],
	["Land_Barrel_sand", 1],
	["Land_Barrel_water", 1],
	["Land_arrows_yellow_L", 1],
	["Land_arrows_yellow_R", 1],
	["Land_coneLight", 1],
	["BarrelBase", 2],
	["Fuel_can", 1],
	["Notice_board", 1],
	["Pallets_comlumn", 1],
	["Unwrapped_sleeping_bag", 1],
	["Wheel_barrow", 1],
	["RoadCone", 1],
	["Sign_1L_Border", 1],
	["Sign_Danger", 1],
	["SmallTable", 1],
	["EvPhoto", 1],
	["MetalBucket", 1],
	["Notebook", 1],
	["Radio", 1],
	["SmallTV", 1],
	["Land_Chair_EP1", 1],
	["Suitcase", 1],
	["WeaponBagBase_EP1", 3]
];


/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

/**
 * List of class names of objects moveable by player.
 * Liste des noms de classes des objets transportables par le joueur.
 */
R3F_LOG_CFG_objets_deplacables = R3F_LOG_CFG_objets_deplacables +
[
	"SatPhone", // Needed for the R3F_ARTY module (arty HQ) (nécessaire pour le module R3F_ARTY (PC d'arti))
	"FoldChair_with_Cargo",
	"StaticWeapon",
	"FlagCarrierSmall",
	"Fort_Crate_wood",
	"Fort_RazorWire",
	"Gunrack1",
	"Base_WarfareBBarrier5x",
	"Fort_EnvelopeBig",
	"Fort_EnvelopeSmall",
	"Land_A_tent",
	"Land_Antenna",
	"Land_Fire_barrel",
	"Land_GuardShed",
	"Land_fort_bagfence_corner",
	"Land_fort_bagfence_long",
	"Land_fort_bagfence_round",
	"Land_fortified_nest_small",
	"Land_tent_east",
	"Land_HBarrier_large",
	"Land_Toilet",
	"RoadBarrier_light",
	"WarfareBunkerSign",
	"ACamp",
	"Camp",
	"CampEast",
	"MASH",
	"FlagCarrier",
	"FlagCarrierChecked",
	"Hedgehog",
	"AmmoCrate_NoInteractive_Base_EP1",
	"ReammoBox",
	"TargetE",
	"TargetEpopup",
	"TargetPopUpTarget",
	"Desk",
	"FoldChair",
	"FoldTable",
	"Land_Barrel_empty",
	"Land_Barrel_sand",
	"Land_Barrel_water",
	"Land_arrows_yellow_L",
	"Land_arrows_yellow_R",
	"Land_coneLight",
	"BarrelBase",
	"Fuel_can",
	"Notice_board",
	"Pallets_comlumn",
	"Unwrapped_sleeping_bag",
	"Wheel_barrow",
	"RoadCone",
	"Sign_1L_Border",
	"Sign_Danger",
	"SmallTable",
	"EvPhoto",
	"MetalBucket",
	"Notebook",
	"Radio",
	"SmallTV",
	"Land_Chair_EP1",
	"Suitcase",
	"WeaponBagBase_EP1"
];